### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by annkennedy** [SaberaTalukder/Chen_Institute_DataSAI_for_Neuroscience#5]
Just fyi, I'm unable to clone the full project, seems to be an issue with a file path in the Day 5 material, think there's an extra space after `code` ? cc @tarachari3 

```
error: invalid path '7_11_22_day5_single_cell_and_hypothesis_testing/code /diy_notebooks/countDistrColabExercises.ipynb'
fatal: unable to checkout working tree

```

**Comment by tarachari3** [comment]
Oh! Yes, I must have forgotten to delete this entire folder (I accidentally added a space previously). Either I can do it and submit a pull request, or it can be deleted @SaberaTalukder

**Comment by tarachari3** [comment]
I actually am still able to clone the repository (https). @annkennedy are you still having cloning issues?
Also the whole 7_11_22_day5_single_cell_and_hypothesis_testing/ folder can be deleted (the correct folder is the  07_11_22... one).

**Comment by SaberaTalukder** [comment]
Should be deleted now
